//Naviations
export const HOME_NAVIGATION = "HOME_NAVIGATION"
export const MEDICINES_NAVIGATION = "MEDICINES_NAVIGATION"
//Login
export const LOGIN_SCREEN = "LOGIN_SCREEN"
//Main
export const HOME_SCREEN = "HOME_SCREEN"
export const MEDICINES_SCREEN = "MEDICINES_SCREEN"
export const CREATE_NEW_SYMPTOM_SCREEN = "CREATE_NEW_SYMPTOM_SCREEN"